### ISSUE TITLE
不会配置ctags

### ISSUE THREAD

**Issue by zxcd82** [redguardtoo/find-and-ctags#6]
你好，刚接触emacs没多久，阅读了你在https://github.com/redguardtoo/find-and-ctags/README.org上的说明以及https://github.com/redguardtoo/emacs.d/README.org里的How to use ctags in Emacs effectively链接（http://blog.binchen.org/posts/how-to-use-ctags-in-emacs-effectively-3.html）的上的说明，好像两个说明有点不太一样，直接按照https://github.com/redguardtoo/find-and-ctags/README.org的说明配置，似乎没有生成TAGS文件。能否帮忙解决？
OS：CentOS7.2.1511
emacs：24.3.1
通过终端SSH连接，配置文件copy您的https://github.com/redguardtoo/emacs.d。

**Comment by redguardtoo** [comment]
以我README为准，可以认为是企业版;）照抄示范代码把项目路径还有匹配项目路径的regular expression写对就可以了。只有第一次打开代码文件时才会试图生成TAGS

blog是简化版本，因为面向大多数普通用户，只要说清楚原理就可以了。

**Comment by zxcd82** [comment]
可能是路径和匹配项目路径的regular expression没有写对，以下是我追加在init.el中的代码，请指正，麻烦您了！
注：程序是C++，后缀为.cc
178(add-to-list 'load-path "~/.emacs.d/site-lisp/")
179(require 'find-and-ctags)
180
181(defun my-setup-develop-environment ()
182  (interactive)
183  (let (proj-dir
184        find-opts
185        ctags-opts)
186
187    ;; for COOL MYPROJ
188    ;; you can use find-and-ctags-current-full-filename-match-pattern-p instead
189    (when (find-and-ctags-current-path-match-pattern-p "emacs_learn._/programe")
190      (setq proj-dir ("~/emacs_learn/files/programe"))
191      ;; ignore file bigger than 64K, ignore files in "dist/"
192      (setq find-opts "-not -size +64k -not -iwholename '_/dist/_'")
193      (setq ctags-opts "--exclude='_.min.js' --exclude='_.git_'")
194      ;; you can use setq-local instead
195      (setq tags-table-list
196            (list (find-and-ctags-run-ctags-if-needed proj-dir '((find-opts ctags-opts)
197                                                                 ("dist/test.js" "-a"))))))
198    ;; for other projects
199    ;; insert more `when' statements here
200    ))
201
202  ;; OPTIONAL
203  (add-hook 'after-save-hook 'find-and-ctags-auto-update-tags)
204  (add-hook 'prog-mode-hook 'my-setup-develop-environment)
205  (add-hook 'org-mode-hook 'my-setup-develop-environment)

**Comment by redguardtoo** [comment]
Yes, maybe you need tweak ctags-opts a little bit, depending on your project, see https://www.topbug.net/blog/2012/03/17/generate-ctags-files-for-c-slash-c-plus-plus-source-files-and-all-of-their-included-header-files/ 

It's optional.

**Comment by zxcd82** [comment]
谢谢你的链接，外部头文件包含的方法很不错，不过以上我粘贴的init.el中的代码应该有问题，我打开了~/emacs_learn/files/programe里的代码文件之后，没有生成TAGS，是否能指点。

**Comment by redguardtoo** [comment]
因为我的sample写的过于复杂了，导致你修改的时候产生了误会。我已更新了readme。

``` lisp
(require 'find-and-ctags)

(defun my-setup-develop-environment ()
  (interactive)

  (when (find-and-ctags-current-path-match-pattern-p "emacs_learn/files/programe")
    ;; ignore file bigger than 64K, ignore files in "dist/"
    ;; you can use setq-local instead
    (setq-local tags-table-list
          (list (find-and-ctags-run-ctags-if-needed "~/emacs_learn/files/programe" ; project directory
                                                    '(("-not -size +64k" "--exclude='.git'") ; (find-opts ctags-opts)
                                                      ;; you may add more find-opts ctags-opts pair HERE to run find&ctags again to APPEND to same TAGS file
                                                      ;; ctags-opts must contain "-a" to append
                                                      ;; (find-opts "-a")
                                                      )))))
  ;; for other projects
  ;; insert more `when' statements here
  )

(add-hook 'prog-mode-hook 'my-setup-develop-environment)
;; OPTIONAL
(add-hook 'after-save-hook 'find-and-ctags-auto-update-tags)
```

**Comment by redguardtoo** [comment]
find-and-ctags我一直在用，比同类插件强大得多，但是宣传不够，用的人少，导致文档有点落伍了。欢迎你多提宝贵意见，如果觉得确实有用的话，帮我多推广

**Comment by zxcd82** [comment]
嗯，按照你修改的代码，没有问题了，可以自动生成TAGS。只是还有一些疑问，
1.如果我定义了(setq find-opts "-not -size +64k")之后，将下面参数"-not -size +64k"替换为find-opts却不能生成TAGS，
2.(setq-local tags-table-list和(setq tags-table-list的区别是不是setq-local会在使用的时候再次提示你选择TAGS，和setq不会。
对不起，对lisp知之甚少，问题比较低能了，可能懂lisp的人一看代码就知道问题所在。

**Comment by redguardtoo** [comment]
1. 牵涉到数组问题，以前写代码时没有用到数组，所以没问题。照我最新版的就行了
2. setq-local 对于当前文件创建一个同名的local的变量，这样你可以在多个文件中使用tags-table-list，但是值不一样。多项目切换需要这个特性。

不会lisp没关系，猜就可以了。一般有国内高中数理化基础的就可以猜出来了。你已比国外绝大多数emacs用户强了。

**Comment by zxcd82** [comment]
好的，大概有点明白了，还有几个问题：
1.关于ctags-opts must contain "-a" to append，我是否可以一直把这个-a参数写上，即使TAGS文件没有生成之前。
2.阅读了你关于“更新版本时保留原有配置 #465 ”的回复（出处：https://github.com/redguardtoo/emacs.d/issues/465 ），我是否将这段find-and-ctags代码移动至 ~/.custom.el比较安全。
3.有没有下一步计划将ctags_with_dep.sh脚本代码的功能增加进去（可能已经有，只是我没有发现，冒昧！），还是因为能效开销会很大而不介意这样做呢？
不过，您的配置真的很不错，让我们一上手就感受到了ide的便利，谢谢！

**Comment by redguardtoo** [comment]
1. 不知道，你可以自己在命令行试一下。好像没什么必要，你是否理解了ctags的“-a”的作用到底是什么？某个目录下有多个代码文件，其中几个文件完全不按照项目命名规范写。所以我们有必要把符合规范的文件生成TAGS，然后针对这几个异类用特定的rule再解析，结果附加到原来的TAGS中去。这种事情在项目中不常有的。
2. 我是都放在`.custom.el`中的
3. 不太熟悉。会考虑采用find的`--new`选项优化，通用性比较强，因我不做C/C++开发，做的是web开发。C的话我觉得目前设置够用了。关键是优化工作流，在一个总目录生成大的TAGS文件，不如在多个子目录里生成多个TAGS文件。`C-h v tags-table-list`，一点Elisp的知识是必要的。

C现在最好的方案是还是用Ctags，C++的话都用GNU Global，性能更好。在我的emacs.d中有关于Global的设置。

同类插件很多，但是其他插件都强调傻瓜友好界面，我则反之，为了强大功能而放弃了友好界面（不可能兼得的，我都仔细计算过了）。所以有一些必要的学习曲线。一点elisp知识， find/ctags的手册都要知道的。

**Comment by zxcd82** [comment]
明白了，暂时感觉Ctags已经够用了，先用着，等有时间再研究。太感谢您的耐心答复，谢谢啦！

**Comment by zxcd82** [comment]
你好，不好意思，又打搅扰了。关于GNU Global的设置，是否按照 “https://github.com/leoliu/ggtags” 里的安装和配置方法进行呢？好像要从源码编译global 和 emacs‘s ctags（/usr/local/bin/ctags）？

**Comment by redguardtoo** [comment]
usually you don't because global and ctags are very popular.

ggtags has its own issue, check its web site, I reported bug there. You may consider using helm-gtags or emacs-counsel-gtags instead.

**Comment by zxcd82** [comment]
OK, thank you very much!
